### ISSUE TITLE
Redundant check for interface type parameters

### ISSUE THREAD

**Issue by luisxkimo** [vgaltes/IoCTesting#1]
Hi Vicenç,

First of all, congratulations for your project. I find it very useful and necessary for us that use IoC containers daily.

I have a small doubt about your testing class. In IoCTesting.cs class on line 71 within the method "CheckTypes", is necessary to check that the type of the parameters "isAbstract" and "isInterface"? If what you need is to know which one is an interface, both methods return true for this data type as the MSDN documentation.

https://msdn.microsoft.com/en-us/library/system.type.isabstract(v=vs.110).aspx

I know my question is silly, but a few days ago in my work I can check that a test that we thought worked, because of this confusion in our case were not working properly.

A greeting!

**Comment by vgaltes** [comment]
Hi,

thanks for your comment. Yes, it seems you are right. Let me test it and I'll push a new version.

Thank you!

**Comment by vgaltes** [comment]
I've just pushed the change (SHA = d9d9f8fc97c360890953d23df091a9f8f56db0d4). 

Thank you very much!

**Comment by luisxkimo** [comment]
Not at all ! :D
